# Modelo machine learning - Prever o comportamento de usuários no site

- Visitante: o campo fullVisitorId representa um visitante único no site. Caso um usuário acesse o site mais de uma vez, atribuir o mesmo fullVisitorId depende da capacidade do Google de identificar o visitante. Se o mesmo usuário acessa o site de diferentes dispositivos ou faz uma limpeza de cookies, ele pode ser considerado um visitante novo no site. Assim como pessoas diferentes que acessem o site do mesmo dispositivo podem ser consideradas o mesmo fullVisitorId.



- Visita: também conhecida como sessão, é identificada na nossa base de dados pelo visitId. Uma sessão é um grupo de interações do usuário com o site que ocorrem dentro de um determinado período de tempo. Um único usuário pode abrir várias sessões. Essas sessões podem ocorrer no mesmo dia ou em vários dias, semanas ou meses.

**Google Analytics**
- O Google Analytics é a ferramenta de Web Analytics do Google. Com ela é possível mensurar o comportamento de usuários em sites e aplicativos.

Para ajudar no treinamento da ferramenta, o Google oferece acesso a conta do Google Analytics da sua loja virtual de brindes.

- Site: shop.googlemerchandisestore.com/

- Conta Analytics Demo: https://analytics.google.com/analytics/web/demoAccount

In [1]:
from platform import python_version

print('Versão python neste Jupyter Notebook:', python_version())

Versão python neste Jupyter Notebook: 3.8.10


In [88]:
import sklearn
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import warnings

warnings.filterwarnings("ignore")

In [91]:
sns.set_palette("Accent")
sns.set(style="whitegrid", color_codes = True, font_scale = 1.6)
color = sns.color_palette()

In [2]:
query = 'SELECT * EXCEPT(hits,customDimensions) FROM `bigquery-public-data.google_analytics_sample.ga_sessions_*` WHERE date BETWEEN "20170301" and "20170331"'

In [3]:
df = pd.read_gbq(query,project_id ='NOME_DO_ID_PROJETO_GCP')

Requesting query... ok.
Job ID: 2419da15-7d3e-48a1-a281-dfb5c7708857
Query running...
  Elapsed 7.07 s. Waiting...
  Elapsed 8.18 s. Waiting...
  Elapsed 9.31 s. Waiting...
  Elapsed 10.42 s. Waiting...
Query done.
Processed: 728.8 MB Billed: 729.0 MB
Standard price: $0.00 USD

Retrieving results...
Got 69931 rows.

Total time taken 64.53 s.
Finished at 2021-08-09 16:55:16.


In [4]:
df.head()

visitorId  visitNumber     visitId  visitStartTime      date  \
0      None            1  1490678716      1490678716  20170327   
1      None            1  1490649820      1490649820  20170327   
2      None            1  1490599273      1490599273  20170327   
3      None            5  1490636932      1490636932  20170327   
4      None            1  1490599368      1490599368  20170327   

                                              totals  \
0  {'sessionQualityDim': None, 'hits': 7, 'unique...   
1  {'sessionQualityDim': None, 'hits': 7, 'unique...   
2  {'sessionQualityDim': None, 'hits': 4, 'unique...   
3  {'sessionQualityDim': None, 'hits': 7, 'unique...   
4  {'sessionQualityDim': None, 'hits': 7, 'unique...   

                                       trafficSource  \
0  {'medium': 'referral', 'referralPath': '/yt/ab...   
1  {'medium': 'referral', 'referralPath': '/yt/ab...   
2  {'medium': 'organic', 'referralPath': None, 's...   
3  {'medium': 'organic', 'referralPath': None, 's...   
4  {'medium': 'referral', 'referralPath': '/yt/ab...   

                                              device  \
0  {'mobileDeviceModel': 'not available in demo d...   
1  {'mobileDeviceModel': 'not available in demo d...   
2  {'mobileDeviceModel': 'not available in demo d...   
3  {'mobileDeviceModel': 'not available in demo d...   
4  {'mobileDeviceModel': 'not available in demo d...   

                                          geoNetwork        fullVisitorId  \
0  {'networkDomain': 'unknown.unknown', 'cityId':...  5841442208033958885   
1  {'networkDomain': 'unknown.unknown', 'cityId':...  9116859201714360991   
2  {'networkDomain': 'unknown.unknown', 'cityId':...  5108227207401232475   
3  {'networkDomain': 'predialnet.com.br', 'cityId...  1506940060110337596   
4  {'networkDomain': 'unknown.unknown', 'cityId':...  2714035062069055929   

  userId clientId channelGrouping  socialEngagementType  
0   None     None          Social  Not Socially Engaged  
1   None     None          Social  Not Socially Engaged  
2   None     None  Organic Search  Not Socially Engaged  
3   None     None  Organic Search  Not Socially Engaged  
4   None     None          Social  Not Socially Engaged

In [5]:
df.shape

(69931, 14)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69931 entries, 0 to 69930
Data columns (total 14 columns):
visitorId               0 non-null object
visitNumber             69931 non-null int64
visitId                 69931 non-null int64
visitStartTime          69931 non-null int64
date                    69931 non-null object
totals                  69931 non-null object
trafficSource           69931 non-null object
device                  69931 non-null object
geoNetwork              69931 non-null object
fullVisitorId           69931 non-null object
userId                  0 non-null object
clientId                0 non-null object
channelGrouping         69931 non-null object
socialEngagementType    69931 non-null object
dtypes: int64(3), object(11)
memory usage: 7.5+ MB


In [7]:
df.totals[0]

{'bounces': None,
 'hits': 7,
 'newVisits': 1,
 'pageviews': 7,
 'screenviews': None,
 'sessionQualityDim': None,
 'timeOnScreen': None,
 'timeOnSite': 515,
 'totalTransactionRevenue': None,
 'transactionRevenue': None,
 'transactions': None,
 'uniqueScreenviews': None,
 'visits': 1}

In [8]:
df.totals[0]

{'bounces': None,
 'hits': 7,
 'newVisits': 1,
 'pageviews': 7,
 'screenviews': None,
 'sessionQualityDim': None,
 'timeOnScreen': None,
 'timeOnSite': 515,
 'totalTransactionRevenue': None,
 'transactionRevenue': None,
 'transactions': None,
 'uniqueScreenviews': None,
 'visits': 1}

In [10]:
# Cada chave (Ex: "browser", "browserVersion", "deviceCategory") dentro dessa coluna, é uma informação a mais sobre essa linha. Sendo assim, para facilitar a nossa manipulação e treino de modelo

dicionarios = ['device','geoNetwork','trafficSource','totals']

In [11]:
# Neste código definimos na variável dicionário carregar cada linhas em uma lista passar para função dataframe e converter em um series
# Basta unir o dataframe original no novo dataframe gerado através função join

for coluna in dicionarios:
  df = df.join(pd.DataFrame([linha for linha in df[coluna]]))

In [12]:
totals = df.totals[0].keys()

In [13]:
totals = list(totals)

In [14]:
df.drop(dicionarios, axis=1, inplace=True)
df.head()

visitorId  visitNumber     visitId  visitStartTime      date  \
0      None            1  1490678716      1490678716  20170327   
1      None            1  1490649820      1490649820  20170327   
2      None            1  1490599273      1490599273  20170327   
3      None            5  1490636932      1490636932  20170327   
4      None            1  1490599368      1490599368  20170327   

         fullVisitorId userId clientId channelGrouping  socialEngagementType  \
0  5841442208033958885   None     None          Social  Not Socially Engaged   
1  9116859201714360991   None     None          Social  Not Socially Engaged   
2  5108227207401232475   None     None  Organic Search  Not Socially Engaged   
3  1506940060110337596   None     None  Organic Search  Not Socially Engaged   
4  2714035062069055929   None     None          Social  Not Socially Engaged   

   ...   pageviews screenviews sessionQualityDim timeOnScreen timeOnSite  \
0  ...         7.0        None              None         None      515.0   
1  ...         7.0        None              None         None      727.0   
2  ...         4.0        None              None         None      268.0   
3  ...         7.0        None              None         None      834.0   
4  ...         7.0        None              None         None     2219.0   

   totalTransactionRevenue transactionRevenue transactions uniqueScreenviews  \
0                      NaN                NaN          NaN              None   
1                      NaN                NaN          NaN              None   
2                      NaN                NaN          NaN              None   
3                      NaN                NaN          NaN              None   
4                      NaN                NaN          NaN              None   

  visits  
0      1  
1      1  
2      1  
3      1  
4      1  

[5 rows x 60 columns]

# Feature Engineering

**Garantir que todas quantitativas estejam identificadas corretamente, vamos usar a função to_numeric em cada uma**

In [15]:
for coluna in totals:
    df[coluna] = pd.to_numeric(df[coluna])
    
df.head()

visitorId  visitNumber     visitId  visitStartTime      date  \
0      None            1  1490678716      1490678716  20170327   
1      None            1  1490649820      1490649820  20170327   
2      None            1  1490599273      1490599273  20170327   
3      None            5  1490636932      1490636932  20170327   
4      None            1  1490599368      1490599368  20170327   

         fullVisitorId userId clientId channelGrouping  socialEngagementType  \
0  5841442208033958885   None     None          Social  Not Socially Engaged   
1  9116859201714360991   None     None          Social  Not Socially Engaged   
2  5108227207401232475   None     None  Organic Search  Not Socially Engaged   
3  1506940060110337596   None     None  Organic Search  Not Socially Engaged   
4  2714035062069055929   None     None          Social  Not Socially Engaged   

   ...   pageviews screenviews sessionQualityDim timeOnScreen timeOnSite  \
0  ...         7.0         NaN               NaN          NaN      515.0   
1  ...         7.0         NaN               NaN          NaN      727.0   
2  ...         4.0         NaN               NaN          NaN      268.0   
3  ...         7.0         NaN               NaN          NaN      834.0   
4  ...         7.0         NaN               NaN          NaN     2219.0   

   totalTransactionRevenue transactionRevenue transactions uniqueScreenviews  \
0                      NaN                NaN          NaN               NaN   
1                      NaN                NaN          NaN               NaN   
2                      NaN                NaN          NaN               NaN   
3                      NaN                NaN          NaN               NaN   
4                      NaN                NaN          NaN               NaN   

  visits  
0      1  
1      1  
2      1  
3      1  
4      1  

[5 rows x 60 columns]

In [16]:
# Na documentação do Google analytics valor Revenue é multiplicado por 1.000.000 para trabalhar número real e dividir coluna 1.000.000

df.totalTransactionRevenue = df.totalTransactionRevenue / 1000000

In [17]:
# Primeira parte do modelo machine learning com os dados possui linha por usuário. Objetivo é prever o valor total gasto por usuário.
# Segundo e treinar o modelo machine learning e agregar as informações do usuário e criar as variaveis preditoras na base de dados.

df_totals = df.groupby('fullVisitorId',as_index=False)[totals].sum()
df_totals

fullVisitorId  sessionQualityDim  hits  uniqueScreenviews  \
0      0000039460501403861                0.0     2                0.0   
1      0000530033766739584                0.0     4                0.0   
2      0000702913088027926                0.0    10                0.0   
3      0000734968258259612                0.0     1                0.0   
4      0001413363431757398                0.0     2                0.0   
5      0002056709015269096                0.0     1                0.0   
6      0002068201793683828                0.0     1                0.0   
7      0002297474409961064                0.0     2                0.0   
8      0002486496724246360                0.0     3                0.0   
9       000282026696553083                0.0     3                0.0   
10     0003036496767745885                0.0     2                0.0   
11     0003098181435381166                0.0     1                0.0   
12     0003458639793126281                0.0     2                0.0   
13     0003614441915948032                0.0     7                0.0   
14     0004021748685969565                0.0     1                0.0   
15     0004050919147348491                0.0     1                0.0   
16     0004476868382641421                0.0     3                0.0   
17     0004608891838688560                0.0     4                0.0   
18     0004615806807819649                0.0     1                0.0   
19      000466292256787683                0.0     1                0.0   
20     0004980249626543698                0.0     4                0.0   
21     0005085643067443862                0.0     6                0.0   
22     0005211946105713074                0.0    16                0.0   
23     0005398476761826798                0.0    13                0.0   
24     0005683171902209290                0.0     1                0.0   
25     0005703676124397865                0.0     7                0.0   
26     0005707952098289710                0.0     3                0.0   
27      000584680858304485                0.0     5                0.0   
28     0006110978733240077                0.0     3                0.0   
29     0006133160743757031                0.0     5                0.0   
...                    ...                ...   ...                ...   
57858  9994825540515462301                0.0     1                0.0   
57859  9994935590271473569                0.0    11                0.0   
57860  9995007670019853217                0.0     3                0.0   
57861  9995088314842334750                0.0     1                0.0   
57862  9995186971896325811                0.0     1                0.0   
57863  9995253261452715957                0.0     1                0.0   
57864  9995685288584307800                0.0     1                0.0   
57865   999586485163436319                0.0     1                0.0   
57866  9995934928001699332                0.0     6                0.0   
57867  9996342168705211685                0.0     1                0.0   
57868  9996387098923414672                0.0     1                0.0   
57869  9996406135255921474                0.0     1                0.0   
57870  9996436469769693414                0.0     1                0.0   
57871  9996860789135335319                0.0     1                0.0   
57872  9996875282707296945                0.0     1                0.0   
57873  9997464307347866920                0.0     1                0.0   
57874  9997712813343429472                0.0    25                0.0   
57875  9997716242882348702                0.0    10                0.0   
57876  9997874500020029581                0.0     2                0.0   
57877  9997902770094104073                0.0     2                0.0   
57878   999801905855509133                0.0     1                0.0   
57879    99980903580581121                0.0     5                0.0   
57880  9998131597

In [18]:
df_totals.shape

(57888, 14)

# Treinamento do modelo M.L

**Neste caso copiar a variável resposta para um variável y**

In [19]:
x = df_totals.drop(['transactionRevenue','totalTransactionRevenue'], axis = 1)
y = df_totals.totalTransactionRevenue.copy()

In [20]:
x.shape

(57888, 12)

In [21]:
y.shape

(57888,)

In [56]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [57]:
x_train.shape

(40521, 12)

In [58]:
y_train.shape

(40521,)

In [59]:
x_test.shape

(17367, 12)

In [60]:
y_test.shape

(17367,)

# Modelo machine learning

**Modelo 01 - Regressão linear**
- Tentar prever o valor gasto por usuário com a regressão linear

In [61]:
from sklearn.linear_model import LinearRegression

model_reg_lin = LinearRegression()
model_reg_lin_fit = model_reg_lin.fit(x_train, y_train)
model_reg_lin_predict = model_reg_lin.predict(x_test)
model_reg_lin_predict

array([2.70935773, 2.68813456, 2.91068411, ..., 2.82231989, 2.87297002,
       2.71276789])

In [62]:
model_reg_lin.intercept_

2.918381932244866

In [63]:
model_reg_lin.coef_

array([-3.58860584e-20,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [64]:
model_reg_lin.coef_ * 27.74456356 + model_reg_lin.intercept_

array([2.91838193, 2.91838193, 2.91838193, 2.91838193, 2.91838193,
       2.91838193, 2.91838193, 2.91838193, 2.91838193, 2.91838193,
       2.91838193, 2.91838193])

In [65]:
x.columns

Index(['fullVisitorId', 'sessionQualityDim', 'hits', 'uniqueScreenviews',
       'timeOnSite', 'newVisits', 'bounces', 'pageviews', 'visits',
       'transactions', 'screenviews', 'timeOnScreen'],
      dtype='object')

In [66]:
# Avaliando performance

result = pd.DataFrame()
result["revenue"] = y_test
result["predict"] = model_reg_lin_predict
result["erro"] = model_reg_lin_predict - y_test

result.head()

revenue   predict      erro
33733      0.0  2.709358  2.709358
37120      0.0  2.688135  2.688135
1227       0.0  2.910684  2.910684
46944      0.0  2.627949  2.627949
31702      0.0  2.898701  2.898701

In [67]:
result[result.revenue > 0].head()

revenue   predict        erro
43035    85.08  2.651793  -82.428207
39840   117.97  2.671493 -115.298507
31853   116.60  2.720783 -113.879217
57216    37.97  2.563864  -35.406136
33173    74.96  2.712838  -72.247162

In [68]:
# Avaliar performance modelo utilizando raiz do erro médio quadrático

import numpy as np

In [69]:
MSE = np.sqrt(np.mean((model_reg_lin_predict - y_test) ** 2))
MSE

35.34186409283866

In [70]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = np.sqrt(mean_squared_error(model_reg_lin_predict, y_test))
print("RMSE Erro quadrático média da raiz:", rmse)

RMSE Erro quadrático média da raiz: 35.34186409283866


In [71]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(model_reg_lin_predict, y_test)
print("MAE Erro médio absoluto:", mae)

MAE Erro médio absoluto: 4.895519860534637


In [72]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(model_reg_lin_predict, y_test)
print("MSE Erro médio quadrático:", mse)

MSE Erro médio quadrático: 1249.047357556679


**Modelo 02 - Gradient Boosting Regressor**

In [73]:
from sklearn.ensemble import GradientBoostingRegressor

model_gradient_reg = GradientBoostingRegressor(random_state = 42)
model_gradient_reg_fit = model_gradient_reg.fit(x_train, y_train)
model_gradient_reg_predict = model_gradient_reg.predict(x_test)
model_gradient_reg_predict

array([-0.07499566, -0.07499566, -0.07499566, ..., -0.07499566,
       -0.07499566, -0.07499566])

In [74]:
model_gradient_reg_predict[model_gradient_reg_predict < 0] = 0
model_gradient_reg_predict

array([0., 0., 0., ..., 0., 0., 0.])

In [75]:
result = pd.DataFrame()
result['revenue'] = y_test
result['predict'] = model_gradient_reg_predict
result['erro'] = model_gradient_reg_predict - y_test
result.head()

revenue  predict  erro
33733      0.0      0.0   0.0
37120      0.0      0.0   0.0
1227       0.0      0.0   0.0
46944      0.0      0.0   0.0
31702      0.0      0.0   0.0

In [76]:
result[result.revenue > 0]

revenue      predict         erro
43035    85.08   119.562100    34.482100
39840   117.97   208.387892    90.417892
31853   116.60    97.415404   -19.184596
57216    37.97    97.415404    59.445404
33173    74.96   206.650972   131.690972
3173     34.98    97.415404    62.435404
11209   196.30    97.415404   -98.884596
4172     32.15    94.039649    61.889649
47601    24.98    97.415404    72.435404
12495    56.99    97.415404    40.425404
34760    22.97   430.208280   407.238280
39638   471.48    97.415404  -374.064596
45455   152.67   143.027272    -9.642728
11028   440.07   137.707562  -302.362438
29177   436.18   414.525921   -21.654079
7586    373.70   119.562100  -254.137900
8492     24.99    97.415404    72.425404
47950    36.98    97.415404    60.435404
36222    72.99    97.415404    24.425404
4028    153.38    97.415404   -55.964596
47279    21.19   204.849207   183.659207
50285   120.96   175.104095    54.144095
23865   121.57   119.562100    -2.007900
6650     15.59   119.562100   103.972100
37395    69.97   105.787351    35.817351
32837    84.58    65.049809   -19.530191
20731    24.79    97.415404    72.625404
44680  1319.63  2008.863647   689.233647
46035    24.19    97.415404    73.225404
33543    93.95    94.039649     0.089649
...        ...          ...          ...
23428    29.99    97.415404    67.425404
18765    24.99   119.562100    94.572100
17466   171.94   300.185255   128.245255
52907  1106.00   200.337087  -905.662913
21335   104.54   176.108203    71.568203
31071    62.99    97.415404    34.425404
36202    51.99   134.343170    82.353170
98       18.99    97.415404    78.425404
2020     33.98   394.764952   360.784952
39820    57.94    97.415404    39.475404
50087    83.99    97.415404    13.425404
196     102.84   208.930000   106.090000
10629    16.98    97.415404    80.435404
30655    48.79    84.161090    35.371090
51986    87.56    97.415404     9.855404
15158   312.72   227.350204   -85.369796
44823    53.97   448.164694   394.194694
49544    61.99    97.415404    35.425404
55956    23.19    97.415404    74.225404
17486    30.98   119.562100    88.582100
47923  1306.35   123.671163 -1182.678837
11463    90.37   554.996690   464.626690
47578   380.52   171.715214  -208.804786
39070   193.20    97.415404   -95.784596
18045    26.99    97.415404    70.425404
48996   280.80   119.562100  -161.237900
35189   199.95    97.415404  -102.534596
27969    61.99    97.415404    35.425404
8600     16.99    97.415404    80.425404
6516    122.13   119.562100    -2.567900

[255 rows x 3 columns]

In [77]:
mse = mean_squared_error(model_gradient_reg_predict, y_test)
mse

1025.474185568343

In [78]:
rmse = np.sqrt(mean_squared_error(model_gradient_reg_predict, y_test))

print("RMSE Erro quadrático média da raiz:", rmse)

RMSE Erro quadrático média da raiz: 32.02302586527924


In [79]:
mae = mean_absolute_error(model_gradient_reg_predict, y_test)

print("MAE Erro médio absoluto:", mae)

MAE Erro médio absoluto: 2.2351400423657424


In [80]:
mse = mean_squared_error(model_gradient_reg_predict, y_test)

print("MSE Erro médio quadrático:", mse)

MSE Erro médio quadrático: 1025.474185568343
